name: "Deploy"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_PATH: HA/HA.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: dotnet publish ${{env.PROJECT_PATH}} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      
      - run: Compress-Archive -Path "HA\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\" -DestinationPath "HA\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\${{ github.ref }}.zip"
      - uses: csexton/release-asset-actions@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pattern: HA\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\
          release|_url: ${{steps.create_release.outputs.upload_url}}
